# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=128)),
                ('itemID', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('itemPic', models.ImageField(blank=True, upload_to='item_images')),
                ('description', models.TextField(blank=True)),
                ('datePosted', models.DateField(auto_now=True)),
                ('sold', models.BooleanField(default=False)),
                ('condition', models.CharField(default='', max_length=128)),
                ('dailyVisits', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('ageGroup', models.CharField(default='', max_length=128)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('postcode', models.CharField(max_length=8)),
                ('rating', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
