# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 17:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('itemPic', models.ImageField(blank=True, upload_to='item_images')),
                ('description', models.TextField(blank=True)),
                ('datePosted', models.DateField(default=datetime.date.today)),
                ('dailyVisits', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d{0,6}$')])),
                ('review', models.TextField(blank=True)),
                ('datePosted', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('postcode', models.CharField(max_length=8)),
                ('rating', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='buyerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailored.Section'),
        ),
        migrations.AddField(
            model_name='item',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='tailored.UserProfile'),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='tailored.UserProfile'),
        ),
    ]
