# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')]),
        ),
    ]
