# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailored', '0002_auto_20190316_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')]),
        ),
    ]
